# Список доменов, с которых разрешено обращение к серверу. Разделитель - ';'
AllowedHosts: '*'

# Список адресов, на которых будет запущен сервер. Разделитель - ';'
Urls: http://localhost:5000

# Секция для указания строк подключения
ConnectionStrings: ""
