GoogleAuthentication:
  AuthorizationEndpoint: https://accounts.google.com/o/oauth2/v2/auth
  TokenEndpoint: https://oauth2.googleapis.com/token
  UserInformationEndpoint: https://www.googleapis.com/oauth2/v1/userinfo
  IdJsonKey: id
  NameJsonKey: name
  EmailJsonKey: email
  Scopes:
    - https://www.googleapis.com/auth/userinfo.profile
    - https://www.googleapis.com/auth/userinfo.email
JwtAuthentication:
  ExpiryMinutes: 30
  Issuer: http://localhost:5000
  Audience: http://localhost:5000
